---
title: "Course Schedule"
tbl-colwidths: [5,10,20,20,25,5,5,5,5]
editor: visual
---

```{r}
#| label: setup
#| include: false
library(lubridate)

sun <- as_date("2026-05-17")
mon <- sun+days(1)
tues <- sun+days(2)
wed <- sun+days(3)
thur <- sun+days(4)
fri <- sun+days(5)
sat <- sun+days(6)

advdate <- function(day, week) {
  date <- (day + weeks(week))
  dm <- paste(month(date, label = TRUE)," ", day(date))
  return(dm)  
}
```

This page displays an outline of the topics, content, and assignments for the term. Each module starts on a Monday. There are no assignments due on Sundays.

::: column-screen-inset-right
| Module | Date | Skills | Packages | Functions | Readings | Videos | Assignments |
|:--:|----|----|----|----|:--:|----|:--:|
| [GS](/modules/getting-started.qmd "Getting Started") | `r advdate(sun,0)` | R, RStudio, GitHub |  |  | [📖](https://rstudio-education.github.io/hopr/starting.html "hopwr, Appendix A and B") [📖](https://quarto.org/docs/get-started/hello/rstudio.html "Hello, Quarto") | [🖥️](https://youtu.be/eimM6pNkYjE "Getting Started with R and RStudio") [🖥️](https://youtu.be/6QN9ZYURDFg "Your First Quarto Document") [🖥️](https://youtu.be/ApvMnAfQe8A "Getting Started With GitHub") |  |
| [1.1](/modules/module-1.1.html "Module 1.1") | `r advdate(mon,0)` | Read data into R | `readr`, `dplyr` | `read_csv()`, `glimpse()` | [📖](https://r4ds.hadley.nz/data-import.html#introduction "r4ds 8.1 & 8.2") | [🖥️](https://youtu.be/ZwJsSjJRuMU "Reading data into R") |  |
|  | `r advdate(tues,0)` | Reshape data | `tidyr` | `pivot_longer()` | [📖](https://r4ds.hadley.nz/data-tidy.html "r4ds 6.1 & 6.3") | [🖥️](https://youtu.be/u4AXi8A1Bqo "Reshaping data") |  |
|  | `r advdate(wed,0)` | Clean data | `dplyr` | `mutate()`, `mutate_at()`, `substring()` |  | [🖥️](https://youtu.be/xa0tYCfHHTI "Cleaning data in R") | [📘](/quiz.html "Module quiz available on course LMS") |
| [1.2](/modules/module-1.2.html "Module 1.2") | `r advdate(thur,0)` | Download data from an API | `wbstats`, `vdemdata`, `dplyr`, `janitor` | `wb_data()`, `vdem`, `select_()`, `filter()`, `case_match()`, `round_to_fraction()` |  | [🖥️](https://youtu.be/Z_jEYnRBv4M "Dowload data from the World Bank") [🖥️](https://youtu.be/ScQD47eJeAE "Download data from V-Dem") |  |
|  | `r advdate(fri,0)` | Merge data frames | `countrycode`, `dplyr` , `readr` | `countrycode()`, `left_join()`, `write_csv()` | [📖](https://r4ds.hadley.nz/joins.html#sec-mutating-joins "r4ds, 20.3") | 🖥️ |  |
|  | `r advdate(sat,0)` | Group, summarize and arrange | `dplyr` | `group_by()`, `summarize()`, `arrange()` | [📖](https://link.springer.com/article/10.1057/palgrave.ap.5500151 "Norris") [📖](https://r4ds.hadley.nz/data-transform.html#groups "r4ds, 4.5") | [🖥️](https://youtu.be/mgBwVzMV-v8 "Group, summarize and arrange") | [📘](/quiz.html "Module quiz available on course LMS") [🧮](/assignments/coding-assignment-1.html "Coding assignment 1") |
| [2.1](/modules/module-2.1.html "Module 2.1") | `r advdate(mon,1)` | Bar charts & histograms | `ggplot2` | `ggplot()`, `geom_col()`, `geom_histogram()`, `aes()`, `labs()` | [📖](https://r4ds.hadley.nz/data-visualize.html "r4ds, 2")[📖](https://r4ds.hadley.nz/communication.html#labels "r4ds, 12.2") | [🖥️](https://youtu.be/hl02sVTyCRA "Bar charts") [🖥️](https://youtu.be/LuNDAIQXx9w "Histograms") |  |
|  | `r advdate(tues,1)` | Line charts | `ggplot2` | `geom_line()` |  | [🖥️](https://youtu.be/cHos9y261SQ "Line charts") |  |
|  | `r advdate(wed,1)` | Scatter plots | `ggplot2`, `scales` | `geom_point()`, `geom_smooth()`, `scale_x_log10(),` `label_number()`, `geom_text()` | [📖](https://r4ds.hadley.nz/layers.html "r4ds, 10.1-10.4") | [🖥️](https://youtu.be/Cvme3C268wE "Scatter plots") | [📘](/quiz.html "Module quiz available on course LMS") |
| [2.2](/modules/module-2.2.html "Module 2.2") | `r advdate(thur,1)` | Color schemes | `tidyr`, `colorBlindess`, `dplyr`, `viridis`, `RColorBrewer` | `drop_na()`, `cvdPlot()`, `scale_fill_manual()`, `scale_fill_viridis_d()`, `scale_fill_brewer()`, `scale_color_manual()`, `scale_color_viridis_d()`, `scale_color_brewer` | [📖](https://r4ds.hadley.nz/communication.html#scales "r4ds, 12.4") | [🖥️](https://youtu.be/fBCtSjg_-Ik "Color schemes") |  |
|  | `r advdate(fri,1)` | Themes & annotations | `ggplot2` | `theme_dark()`, `theme_minimal()`, `annotate()`, `geom_hline()`, `geom_vline()` | [📖](https://r4ds.hadley.nz/communication.html#annotations "r4ds, 12.3 & 12.5") | [🖥️](https://youtu.be/Le0OJXdsy3o "Themes") [🖥️](https://youtu.be/uEpBMgWilXc "Annotations") |  |
|  | `r advdate(sat,1)` | Interactivity | `plotly` | `ggplotly()`, `layout()` | [📖](https://www-jstor-org.proxygw.wrlc.org/stable/1951731?seq=8 "Lipset") | [🖥️](https://youtu.be/T-7jtbcwaJ0 "Interactivity") | [📘](/quiz.html "Module quiz available on course LMS") [🧮](/assignments/coding-assignment-2.html "Coding assignment 2") |
| [3.1](/modules/module-3.1.html "Module 3.1") | `r advdate(mon,2)` | Choropleth maps | `rnaturalearth`, `ggplot2`, `ggthemes` | `ne_countries()`, `geom_sf()`, `theme_map()` |  | [🖥️](https://youtu.be/HB3PMF93hzs "Choropleth maps") |  |
|  | `r advdate(tues,2)` | Map data | `ggplot2`, `viridis` | `theme()`, `scale_fill_viridis_c()` |  | [🖥️](https://youtu.be/5RnnGov3Iw4 "Map World Bank data") |  |
|  | `r advdate(wed,2)` | Make a map function |  | `eval()`, `parse()`, `function()`, `source()` |  | [🖥️](https://youtu.be/m42vrbEEHT4 "Turn your map into a function") | [📘](/quiz.html "Module quiz available on course LMS") |
| [3](/modules/module-3.1.html "Module 3.1")[.2](/modules/module-3.2.html "Module 3.2") | `r advdate(thur,2)` | Upload UCDP data | `states`, `sf` | `sfind()`, `st_as_sf()` |  | [🖥️](https://youtu.be/If2PwFv90iI "Upload UCDP data") |  |
|  | `r advdate(fri,2)` | Make a leaflet map | `leaflet` | `leaflet()`, `addTiles()`, `addMarkers()`, `setView()` |  | [🖥️](https://youtu.be/hHUPqgHRqYU "Make a leaflet map") |  |
|  | `r advdate(sat,2)` | Customize your map | `leaflet`, `htmltools` | `awesomeIcons()`, `addAwesomeMarkers(),` `addProviderTiles()`, `sprintf()`, `lapply()`, `HTML` | [📖](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctt7s3wz.10 "Ross, Chapter 3") | [🖥️](https://youtu.be/qLYeSsoDvgs "Customize your map") | [📘](/quiz.html "Module quiz available on course LMS") [🧮](/assignments/coding-assignment-3.html "Coding assignment 3") |
| [4.1](/modules/module-4.1.html "Module 4.1") | `r advdate(mon,3)` | Exploring tabular data | `tidycensus`, `dplyr`, `stringr`, `kableExtra` | `census_api_key()`, `load_variables()`, `get_acs()`, `rename()`, `rename_with`, `str_remove()`, `kable()`, `slice_max()`, `slice_min()`, `slice_sample()`, `bind_rows()` |  | [🖥️](Working%20with%20tidycensus "https://www.youtube.com/embed/wo9vZccmqwc") [🖥️](https://www.youtube.com/embed/wo9vZccmqwc "Explore data with kableExtra") |  |
|  | `r advdate(tues,3)` | Make a `gt` table | `gt` | `gt()`, `tab_header()`, `cols_label()`, `fmt_currency()`, `tab_source_note()`, `cols_width()`, `opt_table_font()`, `cols_align()`, `tab_options()`, `gtsave()` |  | [🖥️](https://www.youtube.com/embed/wo9vZccmqwc "Make a gt table") |  |
|  | `r advdate(wed,3)` | Confidence intervals | `ggplot2` | `geom_errorbar()` |  | [🖥️](https://www.youtube.com/embed/wo9vZccmqwc "Make a coefficient plot") | [📘](/quiz.html "Module quiz available on course LMS") |
| [4.2](/modules/module-4.2.html "Module 4.2") | `r advdate(thur,3)` | Display regression tables | `peacesciencer`, `broom`, `dplyr` | `create_stateyears()`, `add_ucdp_acd()`, `add_democracy()`, `add_creg_fractionalization()`, `add_sdp_gdp()`, `add_rugged_terrain()`, `tidy()`, `mutate_if()`, `glm()`, `binomial()` |  | 🖥️ |  |
|  | `r advdate(fri,3)` | Make regression tables | `modelsummary` | `list()`, `modelsummary()` |  | 🖥️ | [✍️](/project/project-assignment-1.qmd "Project assignment 1") |
|  | `r advdate(sat,3)` | Coefficient plots | `modelsummary` | `modelplot()`, `rev()` | [📖](https://www.jstor.org/stable/3118222 "Fearon & Laitin") | 🖥️ | [📘](/quiz.html "Module quiz available on course LMS") [🧮](/assignments/coding-assignment-4.html "Coding assignment 4") |
| [5.1](/modules/module-5.1.html "Module 5.1") | `r advdate(mon,4)` | Scatter plot app setup | `dplyr` | `summarize_all()` |  | 🖥️ |  |
|  | `r advdate(tues,4)` | Building the UI | `shiny` | `fluidPage()`, `titlePanel()`, `sidebarLayout()`, `sidebarPanel()`, `selectInput()`, `mainPanel()`, `plotOutput()` |  | 🖥️ |  |
|  | `r advdate(wed,4)` | Building the server | `shiny` | `renderPlot()`, `shinyApp()` |  | 🖥️ | [📘](/quiz.html "Module quiz available on course LMS") |
| [5.2](/modules/module-5.2 "Module 5.2") | `r advdate(thur,4)` | Line chart app setup | `fredr` | `fredr_set_key()` , `as.Date()` , `Sys.Date()` , |  | 🖥️ |  |
|  | `r advdate(fri,4)` | Building the UI | `shiny` | `column()`, `wellPanel()`, `helpText()`, `sliderInput()` |  | 🖥️ | [✍️](/project/project-assignment-2.html "Project assignment 2") |
|  | `r advdate(sat,4)` | Building the server | `shiny`, `fredr` | `reactive()`, `fredr()`, `fred_indicator()` | [📖](https://muse-jhu-edu.proxygw.wrlc.org/article/225602 "Huntington") | 🖥️ | [📘](/quiz.html "Module quiz available on course LMS") [🧮](/assignments/coding-assignment-5.html "Coding assignment 5") |
| [6.1](/modules/module-6.1.html "Module 6.1") | `r advdate(mon,5)` | Final Project |  |  |  | 🖥️ |  |
|  | `r advdate(tues,5)` | Final Project |  |  |  |  |  |
|  | `r advdate(wed,5)` | Final Project |  |  |  |  |  |
| [6.2](/modules/module-6.2.html "Module 6.2") | `r advdate(thur,5)` | Final Project |  |  |  | 🖥️ |  |
|  | `r advdate(fri,5)` | Final Project |  |  |  |  |  |
|  | `r advdate(sat,5)` | Final Project |  |  |  |  | [✍️](/project/project-assignment-3.html "Project assignment 3") |
:::
